apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: octi-sync-server
build:
  artifacts:
    - image: ghcr.io/jakob-moeller-cloud/octi-sync-server
      ko:
        dependencies:
          paths: ["**/*.go"]
          ignore: []
manifests:
  kustomize:
    paths:
      - deploy/kustomize/namespace
      - deploy/kustomize
profiles:
  - name: base
    manifests:
      kustomize:
        paths:
          - deploy/kustomize/base
